#!/usr/bin/env bash
# vim: filetype=sh:

TMP_DIR=/tmp/reports

branch=${WERCKER_GIT_BRANCH:-local}
giturl=$(git config --get remote.origin.url)

# If we're not on master or a hotfix branch, skip this script
if [ "$branch" != "master" ]; then
    echo -e "Not on master branch or a hotfix branch, skipping step"
    exit 0
fi

rm -rf $TMP_DIR
git clone $giturl -b gh-pages --single-branch $TMP_DIR
rm -rf $TMP_DIR/*
cp -r target/site/* $TMP_DIR/
pushd $TMP_DIR
git add .
git commit -m "[skip ci] Updating the reporting docs"
git push origin gh-pages --force
